### PR TITLE
add dockerfile

### PR DESCRIPTION
**Pull request by stevenaldinger**
Adds a dockerfile. https://www.docker.com/
Docker basically lets you configure a development environment as code so no one needs to install python/pip/conda on their computers. I wanted to add this in to encourage more people to contribute, it should let people get up and running in 2 minutes.

Building the image:
```
docker build -t eht-imaging .
```

Running the image:

```
docker run -v "$(pwd)":/eht-imaging -it eht-imaging:latest bash
```

At this point you're ready to develop or can cd into `./examples` and run `python example.py`.

### CODE REVIEW

**Comment by mchelen** [comment]
this might be a silly question, but why miniconda2 and not miniconda3?

**Comment by stevenaldinger** [comment]
Not a silly question at all. I started with miniconda3 and was fighting dependency issues I thought might be related to the python version and was unsure what the current maintainers were using in their environment.

After figuring out the dependency issues I never looped back to see if the code was compatible with 3, but I agree that's preferred. Will try to take a look at that tomorrow and update things if I'm able to, thanks for calling that out!

**Comment by mchelen** [comment]
Ah I see, maybe I'll take a look at the miniconda3 image and see if I can get the dependency issues resolved.

On the current file i'm getting an error during build step:
```
running build_ext
  running pre_hook stsci.distutils.hooks.numpy_extension_hook for command build_ext
  
  
  Numpy is required to build this package.
  Please install Numpy on your system first.
  
  hook stsci.distutils.hooks.numpy_extension_hook raised exception: 1
  
  Traceback (most recent call last):
    File "/tmp/pip-install-MrfoNa/pyfits/.eggs/d2to1-0.2.12.post1-py2.7.egg/d2to1/util.py", line 504, in run_command_hooks
      hook_obj(cmd_obj)
    File "/tmp/pip-install-MrfoNa/pyfits/.eggs/stsci.distutils-0.3.7-py2.7.egg/stsci/distutils/hooks.py", line 413, in numpy_extension_hook
      sys.exit(1)
  SystemExit: 1
  
  
  ----------------------------------------
  Failed building wheel for pyfits
  Running setup.py clean for pyfits
  Running setup.py bdist_wheel for pynfft: started
  Running setup.py bdist_wheel for pynfft: finished with status 'error'
  Complete output from command /opt/conda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-MrfoNa/pynfft/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-PiCmcu --python-tag cp27:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-MrfoNa/pynfft/setup.py", line 314, in <module>
      setup_package()
    File "/tmp/pip-install-MrfoNa/pynfft/setup.py", line 306, in setup_package
      extensions = get_extensions()
    File "/tmp/pip-install-MrfoNa/pynfft/setup.py", line 45, in get_extensions
      common_extension_args = get_common_extension_args()
    File "/tmp/pip-install-MrfoNa/pynfft/setup.py", line 32, in get_common_extension_args
      import numpy
  ImportError: No module named numpy
  
  ----------------------------------------
  Failed building wheel for pynfft
  Running setup.py clean for pynfft
  Running setup.py bdist_wheel for simplegeneric: started
  Running setup.py bdist_wheel for simplegeneric: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/a9/28/53/f24776b4c5bcbe91aaf1f1e247bd6fadd17191aa12fac63902
  Running setup.py bdist_wheel for subprocess32: started
  Running setup.py bdist_wheel for subprocess32: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/c0/08/48/bb468e57d688ea6fa40a450d88d7d9f5fb3c955510077da743
  Running setup.py bdist_wheel for scandir: started
  Running setup.py bdist_wheel for scandir: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/91/95/75/19c98a91239878abbc7c59970abd3b4e0438a7dd5b61778335
  Running setup.py bdist_wheel for toolz: started
  Running setup.py bdist_wheel for toolz: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/f4/0c/f6/ce6b2d1aa459ee97cc3c0f82236302bd62d89c86c700219463
Successfully built ephem future html networkx simplegeneric subprocess32 scandir toolz
Failed to build pyfits pynfft
Installing collected packages: pluggy, atomicwrites, more-itertools, attrs, py, funcsigs, pytest, numpy, astropy, ephem, future, h5py, html, scandir, pathlib2, backports.shutil-get-terminal-size, simplegeneric, pygments, ptyprocess, pexpect, ipython-genutils, decorator, traitlets, wcwidth, prompt-toolkit, pickleshare, ipython, python-dateutil, subprocess32, cycler, backports.functools-lru-cache, pytz, pyparsing, kiwisolver, matplotlib, networkx, pandas, pyfits, pynfft, scipy, cloudpickle, PyWavelets, toolz, dask, pillow, scikit-image
  Running setup.py install for pyfits: started
```

**Comment by stevenaldinger** [comment]
Is that this current dockerfile or one you're working on separately? This one was built after fixing two other errors ( https://github.com/achael/eht-imaging/pull/92 ), that's an important disclosure. I wanted to separate the issues/concerns by commit but this dockerfile won't build without the requirements.txt fixes, heads up. I value remember a numpy issue though but I think it went away when I installed with `pip install -r requirements.txt` instead of `pip install .`

**Comment by stevenaldinger** [comment]
Now I'm having the same issue too even off of my master, I can't imagine why unless a version of something changed. I'm about to take the image I have successfully built and dump the versions for requirements.txt and see if that works.

**Comment by stevenaldinger** [comment]
So... I have _no_ explanation for what happened. I pushed up my working image (built when this PR was submitted - https://cloud.docker.com/repository/docker/stevenaldinger/eht-imaging/tags ) to try to collaborate and figure out what's going on with that image that it was able to build when it won't anymore. I thought it was due to versioning (and it still might be) so tried a `pip freeze > requirements.txt` of what was in the image and played with the output for a bit to try to tweak it into working but had no luck.
If you clone down my fork ( https://github.com/stevenaldinger/eht-imaging ), from the master branch and within the repo's root directory you should be able to run: `docker run -v "$(pwd)":/eht-imaging -it stevenaldinger/eht-imaging:latest bash` and work on the repo. It'll work fine without the volume mount but none of your changes will be saved (which I'm sure you know after taking a look at your github profile but for the sake of others reading this, felt like I should be clear).

**Comment by mchelen** [comment]
It looks like the code was developed using python2 since the current `requirements.txt` uses `html` which afaik has been renamed to `html_parser` for python3

**Comment by achael** [comment]
Thank you for putting this together! I am still just starting with docker,  but it's been used extensively by some collaborators in preparing the results (including with eht-imaging). You might be interested in checking out / contributing to the EHT docker library:  https://github.com/eventhorizontelescope/docker-lib

**Pull request merged**
